### ISSUE TITLE
[Feature Request] Min SDK 14 support ?

### ISSUE THREAD

**Issue by peerless2012** [devgianlu/Aria2Android#23]
Is it possiable to support mini sdk 14? Or what is the reason to set mini sdk to api21?

**Comment by devgianlu** [comment]
I need API 21 because it's the first to support Material Design which all my apps are based on. I also suspect that the behavior of services and stuff would be different which makes backward compatibility a pain.

This would also mean to add support for 0.3% more devices which is a bit low. ([Source](https://developer.android.com/about/dashboards))

**Comment by peerless2012** [comment]
Material Design support low to api 14，so it may be enable to support api 14 and above。
